name: Build mema-web

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  build:
    name: Build nuxt app
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Directory
        run: pwd
      - name: List files in dir
        run: ls
