# name: Build mema-web

# # Triggered when code is pushed to any branch in a repository
# on: push

# jobs:
#   build:
#     name: Build nuxt app
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Current Directory
#         run: pwd
#       - name: List files in dir
#         run: ls

name: Build mema-web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print Current Directory
        run: pwd

      - name: List files in dir
        run: ls